name: Build and Release Package

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install RPM tools
      run: sudo apt-get update && sudo apt-get install -y rpm

    - name: Configure CMake
      run: cmake -H. -B_build -DCPACK_GENERATOR="TGZ;DEB;RPM"

    - name: Build and Package
      run: cmake --build _build --target package

    - name: Release Packages
      uses: softprops/action-gh-release@v2
      with:
        files: _build/print_project-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
